services:
  - type: web
    name: cat-vs-dog-classifier
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: PORT
        value: 8000
    pythonVersion: 3.9